apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: production
  labels:
    app: frontend-web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      priorityClassName: production-critical
      containers:
        - name: frontend-web
          image: nginx:v99.99.99-nonexistent-tag    # Invalid image tag!
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
